name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cc65 install
      run: sudo apt-get install cc65

    - name: Make ROM
      run: |
        cd src
        make

    - name: Make programs
      run: |
        cd src
        make utils
