name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Enter src
      run: cd src

    - name: Make ROM
      run: make

    - name: Make programs
      run: make utils
