name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cc65 install
      run: sudo apt-get install cc65

    - name: Make ROM
      run: |
        cd src
        make

    - name: Make programs
      run: |
        cd src
        make utils

      # Upload artifacts
    - name: Archive 8K ROM
      uses: actions/upload-artifact@v3
      with:
          name: tib001-8K.bin
          path: src/build/tib001.bin

    - name: Archive 16K ROM (low 8K new, high 8K old ROM)
      uses: actions/upload-artifact@v3
      with:
          name: tib001-16K.bin
          path: src/build/tib001-16k.bin

    - name: Archive tools for new ROM
      uses: actions/upload-artifact@v3
      with:
          name: tib001-new-tools.zip
          path: src/build/*.prg
